variables:
  Parameters.RestoreBuildProjects: '**/BlazorPongServer.csproj'
  Parameters.TestProjects: '**/*Tests/*.csproj'
  BuildPlatform: 'x86'
  buildConfiguration: 'Release'
  Parameters.ArtifactName: 'Drop'

pool:
  name: Hosted Windows 2019 with VS2019

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 3.x'
  inputs:
    version: '3.0.100-preview8-013656'
    includePreviewVersions: true
  enabled: false
  timeoutInMinutes: 5

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '$(Parameters.RestoreBuildProjects)'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '$(Parameters.RestoreBuildProjects)'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '$(Parameters.TestProjects)'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    publishWebProjects: false
    projects: '$(Parameters.RestoreBuildProjects)'
    arguments: '--configuration $(BuildConfiguration) -r win-x86 --self-contained true --output $(build.artifactstagingdirectory) /p:EnvironmentName=Production'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'

