version: '3.8'

networks:
  corp:
    driver: bridge

services:
  mssql01:
    container_name: mssql01
    image: mcr.microsoft.com/mssql/server:2019-latest
    networks:
      - corp
    ports:
      - '1433:1433'
    environment: 
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: yourStrong(!)Password
      MSSQL_PID: Express

  aspnetcoreapp:
    image: macel94/blazorpongwasm_aspnetcoreapp
    container_name: aspnetcoreapp
    networks:
      - corp
    ports:
      - '5000:80'
      - '5001:443'
    environment: 
      ASPNETCORE_URLS: http://+:5000
    depends_on:
      - 'mssql01'

  reverse-proxy:
    container_name: reverse-proxy
    volumes:
      - /root/certs-data/:/data/letsencrypt/
      - /etc/letsencrypt/:/etc/letsencrypt/
    networks:
      - corp
    image: macel94/blazorpongwasm_reverse-proxy
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - 'aspnetcoreapp'