#docker-compose -f "Docker-Compose.dev.wasm.yml" up --build
#docker-compose -f "Docker-Compose.dev.wasm.yml" down --remove-orphans
#docker-compose -f "Docker-Compose.dev.wasm.yml" kill
version: '3.8'

networks:
  corp:
    driver: bridge

services:
  aspnetcoreapp:
    image: macel94/blazorpongwasm_aspnetcoreapp
    build:
      context: .
      dockerfile: Dockerfile-BlazorPongWasm-Server
    container_name: aspnetcoreapp
    networks:
      - corp
    ports:
      - '5000:80'
      - '5001:443'
    environment: 
      ASPNETCORE_URLS: http://+:5000

  reverse-proxy:
    image: macel94/blazorpongwasm_reverse-proxy
    container_name: reverse-proxy
    volumes:
      - ./NGINX/DEV/root/certs-data/:/data/letsencrypt/
      - ./NGINX/DEV/etc/letsencrypt/:/etc/letsencrypt/
    networks:
      - corp
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - 'aspnetcoreapp'
